### ISSUE TITLE
Use connectingtoservices specific google analytics id.

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsalpha/gp-to-services#50]
From slack discussion:

Dom Smith [3:28 PM]  
@neilbmclaughlin: just picking up the analytics conversation again
noticed you mentioned about using the same property ID as beta.nhs.uk for the gp-to-services app
what was the reason again?
I’m thinking we should keep these as separate properties for now unless they’re sat on the same domain
means we don’t have to mess around with filters at this stage and stops the analytics having mixed data
also, would recommend setting the id in the layout file as an environment variable so that you can change the analytics per environment
you probably won’t want the GA property getting hit with page views when you’re working locally so not to skew the data

Neil McLaughlin [8:32 PM]  
@domsmith: the decision came about following a discussion with Joe McGrath where we felt it could be resolved at the reporting level but happy to use another ID if it causes problems. thanks for the suggestion to store the id in an env var - i’ll raise both issues in github and we’ll resolve it soon.

**Comment by st3v3nhunt** [comment]
Closing issue as #57 has been merged
